version: "3"


services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 1443:1443
    networks:
      - app
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    ports:
      - 8080:5000
    environment:
      PYTHONBUFFERED: "1"
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    networks:
      - app
    env_file:
      - .env
    tty: true



  postgres_db:
    image: postgres:latest
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

    volumes:
      - ./db:/var/lib/postgresql/data/
    networks:
      - app



networks:
  app:
    driver: bridge
